### ISSUE TITLE
Installation instructions unclear - Only shows up under Application Style

### ISSUE THREAD

**Issue by legrassy** [michaldybczak/MaiaTransparent-plasma-theme#2]
I unpacked and copied the folder in both files paths provided and I cannot see the Maia Transparent theme in "Global Theme"
only reference is under "Application Style" 

``` 
  unzip MaiaTransparent-plasma-theme-main.zip  
  cp -r MaiaTransparent-plasma-theme-main ~/.local/share/plasma/desktoptheme/  
  sudo cp -r MaiaTransparent-plasma-theme-main /usr/share/plasma/desktoptheme/  
```

![image](https://user-images.githubusercontent.com/23105991/109917329-bcc7d800-7c7a-11eb-8ac4-8efdcf67f571.png)
![image](https://user-images.githubusercontent.com/23105991/109917368-d0733e80-7c7a-11eb-9211-b222a04b2593.png)

KDE Plasma Version: 
![image](https://user-images.githubusercontent.com/23105991/109917696-5d1dfc80-7c7b-11eb-9919-477e56d89c61.png)

**Comment by michaldybczak** [comment]
Maia Transparent is not a global theme but a desktop theme, so this is a correct behavior. Note that Maia Transparent is under Plasma Themes, not in Global Themes category on https://store.kde.org . Also, when you find new components from the desktop, you can also find Maia Transparent from Plasma Style, not from Global Theme.

Global themes contain many components together: desktop theme, color theme, icon theme, aurorae (titlebar) theme, window look theme, cursor theme, font theme, etc.

In my experience, only few use global themes. KDE users like to tweak and have control over various desktop elements and that is why, you set your desktop theme and then set other desktop elements as you wish. However, I noticed that lately Global Themes became a bit more popular and some good Global Themes showed up.

At the moment, if you like most of the components of some global theme but prefer to have a fully transparent desktop theme, simply apply that global theme first and then replace the desktop theme for Maia Transparent.

**Comment by legrassy** [comment]
Thank you for the clarification
